# Generated by Django 6.0 on 2025-12-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AracKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('aciklama', models.TextField(blank=True)),
                ('sira', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Araç Kategorisi',
                'verbose_name_plural': 'Araç Kategorileri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='SiteAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_adi', models.CharField(default='Rent a Car', max_length=200)),
                ('site_aktif', models.BooleanField(default=True, verbose_name='Site Aktif mi?')),
                ('meta_description', models.TextField(blank=True, help_text='Ana sayfa meta açıklaması (160 karakter)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Anahtar kelimeler (virgülle ayırın)', max_length=255)),
                ('google_analytics_id', models.CharField(blank=True, help_text='G-XXXXXXXXXX', max_length=50)),
                ('google_ads_id', models.CharField(blank=True, help_text='AW-XXXXXXXXXX', max_length=50)),
                ('google_ads_conversion_label', models.CharField(blank=True, max_length=50)),
                ('google_search_console_verification', models.CharField(blank=True, help_text='Meta verification code', max_length=100)),
                ('gtm_id', models.CharField(blank=True, help_text='GTM-XXXXXXX', max_length=50, verbose_name='Google Tag Manager ID')),
                ('business_phone', models.CharField(blank=True, max_length=20, verbose_name='İşletme Telefonu')),
                ('business_email', models.EmailField(blank=True, max_length=254, verbose_name='İşletme E-posta')),
                ('business_address', models.TextField(blank=True, verbose_name='İşletme Adresi')),
                ('opening_hours', models.CharField(blank=True, default='Mo-Su 09:00-18:00', max_length=100, verbose_name='Çalışma Saatleri')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100, verbose_name='Marka')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('yil', models.IntegerField(verbose_name='Model Yılı')),
                ('yakit_tipi', models.CharField(choices=[('benzin', 'Benzin'), ('dizel', 'Dizel'), ('elektrik', 'Elektrik'), ('hibrit', 'Hibrit')], max_length=20)),
                ('vites_tipi', models.CharField(choices=[('manuel', 'Manuel'), ('otomatik', 'Otomatik')], max_length=20)),
                ('koltuk_sayisi', models.IntegerField(default=5)),
                ('bagaj_hacmi', models.IntegerField(blank=True, help_text='Litre cinsinden', null=True)),
                ('gunluk_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Günlük Fiyat (TL)')),
                ('haftalik_fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Haftalık Fiyat (TL)')),
                ('aylik_fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aylık Fiyat (TL)')),
                ('ana_gorsel', models.ImageField(upload_to='araclar/', verbose_name='Ana Görsel')),
                ('gorsel_2', models.ImageField(blank=True, null=True, upload_to='araclar/')),
                ('gorsel_3', models.ImageField(blank=True, null=True, upload_to='araclar/')),
                ('meta_title', models.CharField(blank=True, help_text='Boş bırakılırsa otomatik oluşturulur', max_length=70)),
                ('meta_description', models.TextField(blank=True, help_text='Boş bırakılırsa otomatik oluşturulur', max_length=160)),
                ('aktif', models.BooleanField(default=True)),
                ('onerilir', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='araclar', to='araclar.arackategori')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
                'ordering': ['-onerilir', '-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Rezervasyon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('mesaj', models.TextField(blank=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('conversion_tracked', models.BooleanField(default=False)),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='araclar.arac')),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
